version: "3"
services:
    autopsy:
        image: bannsec/autopsy:latest
        container_name: autopsy
        shm_size: "2gb"
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - ./case/:/root/case
        environment:
            - DISPLAY=${DISPLAY}
            - JAVA_TOOL_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Djdk.gtk.version=3 -Dsun.java2d.opengl=true'
        networks:
            - host

networks:
    host:
